(define (main state reserved)
    (define (elt2 lst coords)
      (elt (elt lst (car coords)) (cdr coords))
    )
    (define (is-wall grid coords)
      (= 0 (elt2 grid coords))
    )
    (define (vitality man) (car man))
    (define (location man) (elt 1 man))
    (define (at-left coords)
      (pair (cdr coords)
            (- 1 (car coords))
      )
    )
    (define (at-right coords)
      (pair (cdr coords)
            (+ 1 (car coords))
      )
    )
    (define (step ai-state world-state)
      (let (grid (car world-state))
           (man (elt 1 world-state))
        (let (loc (location man))
          (if (is-wall (at-left loc))
            (pair ai-state 1)
            (pair ai-state 3)
          )
        )
      )
    )
    (pair 0 step))
