(define (main state reserved)
    (define (elt2 lst coords)
      (dbug coords)
      (elt (elt lst (car coords)) (cdr coords))
    )
    (define (is-wall grid coords)
      (= 0 (elt2 grid coords))
    )
    (define (vitality man) (car man))
    (define (location man) (elt man 1))
    (define (at-left coords)
      (pair (cdr coords)
            (- (car coords) 1)
      )
    )
    (define (at-right coords)
      (pair (cdr coords)
            (+ 1 (car coords))
      )
    )
    (define (step ai-state world-state)
      (let (grid (car world-state))
        (let (man (elt world-state 1))
          (dbug man)
          (let (loc (location man))
            (dbug loc)
            (if (is-wall grid (at-left loc))
              ((pair ai-state 1))
              ((pair ai-state 3))
            )
          )
        )
      )
    )
    (pair 0 step))
